### ISSUE TITLE
Cache must be cleared each time mapping is updated

### ISSUE THREAD

**Issue by drewclauson** [nilportugues/symfony2-jsonapi-transformer#1]
Any idea why I have to clear my cache every time I update a mapping file in order to see the changes work?

**Comment by nilopc** [comment]
I'm afraid this is normal Symfony2 behaviour.. 

I'm investigating if it's possible to work around it as I understand it's pain to work this way.

**Comment by drewclauson** [comment]
Thanks for looking into it, I looked around a bit but didn't find anything immediately on it.  I'll probably configure a file watcher to clear the cache every time a mapping file is updated for now.
